// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 1cc4b1a09f0bb64266386728966c1f839e386803

package data

// linguist's commit from which files were generated.
var LinguistCommit = "1cc4b1a09f0bb64266386728966c1f839e386803"
